name: lupus_care
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase configuration
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  # flutter_local_notifications: ^19.4.0
  firebase_messaging: ^15.2.10
  cloud_functions: ^5.6.2
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.4.3
  image_cropper: ^9.1.0
  #  purchases_flutter: ^7.0.0
  google_sign_in: ^7.1.1
  connectivity_plus: ^6.1.4

  # Your existing dependencies
  cached_network_image: ^3.4.1
  emoji_picker_flutter: ^4.3.0
  flutter_notification_channel: ^3.1.1
  gallery_saver_plus: ^3.2.8
  lottie: ^3.3.1
  google_generative_ai: ^0.4.7
  http: ^1.4.0
  http_parser: ^4.1.2
  sign_in_with_apple: ^7.0.1
  remixicon: ^1.4.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  dotted_border: ^3.1.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: DMSans_18pt
      fonts:
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/DMSans_18pt-Thin.ttf
          weight: 100
