name: lupus_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase configuration
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
#  flutter_local_notifications: ^15.1.2
  firebase_messaging: ^14.7.9
  cloud_functions: ^4.6.0
  in_app_purchase: ^3.1.11
  in_app_purchase_android: ^0.3.0+15
  in_app_purchase_storekit: ^0.3.8+1
  image_cropper: ^9.1.0
#  purchases_flutter: ^7.0.0
  google_sign_in: ^6.1.5
  connectivity_plus: ^6.0.5


  # Your existing dependencies
  cached_network_image: ^3.2.3
  emoji_picker_flutter: ^2.2.0
  flutter_notification_channel: ^3.1.0
  gallery_saver_plus: ^3.2.1
  lottie: ^3.2.0
  google_generative_ai: ^0.4.3
  http: ^1.4.0
  http_parser: ^4.0.2
  sign_in_with_apple: ^6.1.0
  remixicon: ^1.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: DMSans_18pt
      fonts:
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/DMSans_18pt-Thin.ttf
          weight: 100